# Generated by Django 4.1.4 on 2023-01-13 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='film',
            name='duration',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ageRating',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='ages', to='Customer.film'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='descriptions', to='Customer.film'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='duration',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='durations', to='Customer.film'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='titles', to='Customer.film'),
        ),
    ]
