services:
  django_docker:
    image: django_docker
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    entrypoint: ["./django_docker-entrypoint.sh"]